// Generated by Wrangler on Fri Mar 21 2025 03:17:04 GMT+0530 (India Standard Time)
// by running `wrangler types`

import { BrowserWorker } from '@cloudflare/puppeteer';

interface Env {
	BROWSER_KV: KVNamespace;
	BACKEND_SECURITY_TOKEN: string;
	BROWSER: DurableObjectNamespace /* Browser */;
	RENDER_RATE_LIMITER: any;
	MFBROWSER: BrowserWorker;
	AI_AGENT: Ai;
}
